### ISSUE TITLE
Create Swagger API description for the Registry

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/spe-app-registry-etcd#1]
Use Swagger [1] to create a description file for the API of the ETCD registry.

REST-endpoints must include:
* List app information on an app-id
* List the information of all apps

Location to save the swagger file:
Resources/Documentation/API/swagger.yaml

[1] https://swagger.io/

Priority: low

**Comment by Kuhno92** [comment]
Api description now available under Resources/Documentation/API 0111c3da164a3a1bc524c9ee62c06d8b45d81a5b
